# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "trusty-vmware"
  config.vm.network "forwarded_port", guest: 3000, host: 3333

  config.vm.synced_folder "../www", "/var/www"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.define "bladesbox" do |bladesbox|
    bladesbox.vm.hostname = "bladesbox"
  end

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = "modules"
  end
end
